"""add social profiles, image evidence and analyst decisions

Revision ID: 0b7a3f57d87e
Revises: a12e580fbbc3
Create Date: 2026-09-07 21:18:11.372021
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.models.types
from alembic import op

revision: str = "0b7a3f57d87e"
down_revision: str | None = "a12e580fbbc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyst_decisions",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("case_id", app.models.types.GUID(), nullable=False),
        sa.Column(
            "subject_type",
            sa.Enum(
                "CANDIDATE",
                "SOCIAL_PROFILE",
                "IMAGE",
                name="decision_subject",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("subject_id", app.models.types.GUID(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "CONFIRMED",
                "REJECTED",
                "UNRESOLVED",
                "NEEDS_REVIEW",
                name="analyst_decision",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("decided_by", sa.String(length=200), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "case_id", "subject_type", "subject_id", name="uq_decision_case_subject"
        ),
    )
    with op.batch_alter_table("analyst_decisions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_analyst_decisions_case_decision", ["case_id", "decision"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_analyst_decisions_case_id"), ["case_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_analyst_decisions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_analyst_decisions_subject_id"), ["subject_id"], unique=False
        )

    op.create_table(
        "social_profiles",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("case_id", app.models.types.GUID(), nullable=False),
        sa.Column("candidate_entity_id", app.models.types.GUID(), nullable=True),
        sa.Column("target_id", app.models.types.GUID(), nullable=True),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("platform_label", sa.String(length=100), nullable=False),
        sa.Column("handle", sa.String(length=200), nullable=True),
        sa.Column("profile_url", sa.String(length=2048), nullable=False),
        sa.Column("display_name", sa.String(length=300), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "accessibility",
            sa.Enum(
                "PUBLIC",
                "RESTRICTED",
                "UNKNOWN",
                name="profile_access",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("server_fetchable", sa.Boolean(), nullable=False),
        sa.Column("fetch_note", sa.Text(), nullable=True),
        sa.Column("collector", sa.String(length=64), nullable=False),
        sa.Column("evidence_class", sa.String(length=40), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "match_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "mismatch_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "corroborated_by",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["candidate_entity_id"], ["entities.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "profile_url", name="uq_social_profile_case_url"),
    )
    with op.batch_alter_table("social_profiles", schema=None) as batch_op:
        batch_op.create_index("ix_social_profiles_candidate", ["candidate_entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_social_profiles_case_id"), ["case_id"], unique=False)
        batch_op.create_index(
            "ix_social_profiles_case_platform", ["case_id", "platform"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_social_profiles_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_social_profiles_handle"), ["handle"], unique=False)
        batch_op.create_index(batch_op.f("ix_social_profiles_platform"), ["platform"], unique=False)

    op.create_table(
        "image_evidence",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("case_id", app.models.types.GUID(), nullable=False),
        sa.Column("candidate_entity_id", app.models.types.GUID(), nullable=True),
        sa.Column("social_profile_id", app.models.types.GUID(), nullable=True),
        sa.Column("image_url", sa.String(length=2048), nullable=False),
        sa.Column("source_page_url", sa.String(length=2048), nullable=False),
        sa.Column("platform", sa.String(length=100), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("context_text", sa.Text(), nullable=True),
        sa.Column(
            "fetch_state",
            sa.Enum(
                "FETCHED",
                "REFERENCE_ONLY",
                "BLOCKED",
                name="image_fetch_state",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("byte_length", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column(
            "redirects",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("final_url", sa.String(length=2048), nullable=True),
        sa.Column("fetch_note", sa.Text(), nullable=True),
        sa.Column("origin", sa.String(length=64), nullable=False),
        sa.Column("evidence_class", sa.String(length=40), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence_id", app.models.types.GUID(), nullable=True),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["candidate_entity_id"], ["entities.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["social_profile_id"], ["social_profiles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "case_id", "image_url", "source_page_url", name="uq_image_case_url_page"
        ),
    )
    with op.batch_alter_table("image_evidence", schema=None) as batch_op:
        batch_op.create_index(
            "ix_image_evidence_case_candidate", ["case_id", "candidate_entity_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_image_evidence_case_id"), ["case_id"], unique=False)
        batch_op.create_index(
            "ix_image_evidence_case_platform", ["case_id", "platform"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_image_evidence_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_image_evidence_fetch_state"), ["fetch_state"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_image_evidence_sha256"), ["sha256"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("image_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_image_evidence_sha256"))
        batch_op.drop_index(batch_op.f("ix_image_evidence_fetch_state"))
        batch_op.drop_index(batch_op.f("ix_image_evidence_created_at"))
        batch_op.drop_index("ix_image_evidence_case_platform")
        batch_op.drop_index(batch_op.f("ix_image_evidence_case_id"))
        batch_op.drop_index("ix_image_evidence_case_candidate")

    op.drop_table("image_evidence")
    with op.batch_alter_table("social_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_social_profiles_platform"))
        batch_op.drop_index(batch_op.f("ix_social_profiles_handle"))
        batch_op.drop_index(batch_op.f("ix_social_profiles_created_at"))
        batch_op.drop_index("ix_social_profiles_case_platform")
        batch_op.drop_index(batch_op.f("ix_social_profiles_case_id"))
        batch_op.drop_index("ix_social_profiles_candidate")

    op.drop_table("social_profiles")
    with op.batch_alter_table("analyst_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analyst_decisions_subject_id"))
        batch_op.drop_index(batch_op.f("ix_analyst_decisions_created_at"))
        batch_op.drop_index(batch_op.f("ix_analyst_decisions_case_id"))
        batch_op.drop_index("ix_analyst_decisions_case_decision")

    op.drop_table("analyst_decisions")
    # ### end Alembic commands ###
