"""record execution observations

One table, so that "execution X observed object O, in this state" becomes a fact
the database holds rather than one a report has to guess at. The canonical tables
stay canonical; this records observations of them.

**There is no backfill, deliberately.** Findings, evidence, entities,
relationships, profiles, contacts and images that predate this table get no
observation rows. Inventing rows would attribute them to an execution that may
never have seen them, which is the same class of false claim the table exists to
prevent. An execution with no rows is reported as having no observation ledger —
told apart from one that genuinely observed nothing by the ``observations_recorded``
flag the engine writes onto a job's result. Legacy executions have neither, and
the report says exactly that.

The downgrade drops the table and loses the ledger. Nothing else depends on it:
the canonical tables are untouched by this migration, so a downgrade returns the
database to case-level-only reporting without losing a single finding.

Revision ID: 583ddee18357
Revises: 5dd52620747d
Create Date: 2026-09-11 21:39:07.043867
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.models.types
from alembic import op

revision: str = "583ddee18357"
down_revision: str | None = "5dd52620747d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_observations",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("case_id", app.models.types.GUID(), nullable=False),
        sa.Column("job_id", app.models.types.GUID(), nullable=True),
        sa.Column("run_id", app.models.types.GUID(), nullable=True),
        sa.Column(
            "stage",
            sa.Enum(
                "COLLECTION",
                "SEARCH",
                "PROMOTION",
                "CORRELATION",
                "IMPORT",
                name="observation_stage",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "subject_type",
            sa.Enum(
                "FINDING",
                "EVIDENCE",
                "ENTITY",
                "RELATIONSHIP",
                "SOCIAL_PROFILE",
                "PUBLIC_CONTACT",
                "IMAGE_EVIDENCE",
                name="observation_subject",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("subject_id", app.models.types.GUID(), nullable=False),
        sa.Column("collector", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_seen", sa.Boolean(), nullable=False),
        sa.Column(
            "state",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["collector_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "job_id", "subject_type", "subject_id", name="uq_observation_execution_subject"
        ),
    )
    with op.batch_alter_table("execution_observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_execution_observations_case_id"), ["case_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_execution_observations_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_execution_observations_job_id"), ["job_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_execution_observations_subject_id"), ["subject_id"], unique=False
        )
        batch_op.create_index(
            "ix_observations_case_subject", ["case_id", "subject_type", "subject_id"], unique=False
        )
        batch_op.create_index("ix_observations_job_kind", ["job_id", "subject_type"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("execution_observations", schema=None) as batch_op:
        batch_op.drop_index("ix_observations_job_kind")
        batch_op.drop_index("ix_observations_case_subject")
        batch_op.drop_index(batch_op.f("ix_execution_observations_subject_id"))
        batch_op.drop_index(batch_op.f("ix_execution_observations_job_id"))
        batch_op.drop_index(batch_op.f("ix_execution_observations_created_at"))
        batch_op.drop_index(batch_op.f("ix_execution_observations_case_id"))

    op.drop_table("execution_observations")
    # ### end Alembic commands ###
