"""add public contacts

Revision ID: 5dd52620747d
Revises: 0b7a3f57d87e
Create Date: 2026-09-09 05:02:48.092620
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.models.types
from alembic import op

revision: str = "5dd52620747d"
down_revision: str | None = "0b7a3f57d87e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "public_contacts",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("case_id", app.models.types.GUID(), nullable=False),
        sa.Column("candidate_entity_id", app.models.types.GUID(), nullable=True),
        sa.Column("social_profile_id", app.models.types.GUID(), nullable=True),
        sa.Column(
            "contact_type",
            sa.Enum(
                "EMAIL",
                "PHONE",
                "WEBSITE",
                "CONTACT_PAGE",
                name="contact_type",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=500), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=True),
        sa.Column(
            "classification",
            sa.Enum(
                "VERIFIED_PUBLIC_BUSINESS",
                "PUBLIC_PROFESSIONAL",
                "PUBLIC_SELF_PUBLISHED",
                "UNVERIFIED_PUBLIC_REFERENCE",
                name="contact_classification",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column("collector", sa.String(length=64), nullable=False),
        sa.Column("evidence_class", sa.String(length=40), nullable=False),
        sa.Column("evidence_id", app.models.types.GUID(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "confidence_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("extraction_reason", sa.Text(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["candidate_entity_id"], ["entities.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["social_profile_id"], ["social_profiles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "case_id", "contact_type", "value", name="uq_public_contact_case_value"
        ),
    )
    with op.batch_alter_table("public_contacts", schema=None) as batch_op:
        batch_op.create_index("ix_public_contacts_candidate", ["candidate_entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_public_contacts_case_id"), ["case_id"], unique=False)
        batch_op.create_index(
            "ix_public_contacts_case_type", ["case_id", "contact_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_public_contacts_classification"), ["classification"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_public_contacts_contact_type"), ["contact_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_public_contacts_created_at"), ["created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("public_contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_public_contacts_created_at"))
        batch_op.drop_index(batch_op.f("ix_public_contacts_contact_type"))
        batch_op.drop_index(batch_op.f("ix_public_contacts_classification"))
        batch_op.drop_index("ix_public_contacts_case_type")
        batch_op.drop_index(batch_op.f("ix_public_contacts_case_id"))
        batch_op.drop_index("ix_public_contacts_candidate")

    op.drop_table("public_contacts")
    # ### end Alembic commands ###
