"""initial schema

Revision ID: 83331975329a
Revises:
Create Date: 2026-09-02 14:37:09.290077
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.models.types
from alembic import op

revision: str = "83331975329a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "RUNNING",
                "PAUSED",
                "COMPLETE",
                "ARCHIVED",
                name="case_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cases_created_at"), "cases", ["created_at"], unique=False)
    op.create_index(op.f("ix_cases_name"), "cases", ["name"], unique=False)
    op.create_index(op.f("ix_cases_status"), "cases", ["status"], unique=False)
    op.create_index("ix_cases_status_created", "cases", ["status", "created_at"], unique=False)
    op.create_table(
        "tags",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_tags_name"),
    )
    op.create_index(op.f("ix_tags_created_at"), "tags", ["created_at"], unique=False)
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=False)
    op.create_table(
        "case_tags",
        sa.Column("case_id", app.models.types.GUID(), nullable=False),
        sa.Column("tag_id", app.models.types.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("case_id", "tag_id"),
    )
    op.create_table(
        "entities",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("case_id", app.models.types.GUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "PERSONA",
                "USERNAME",
                "EMAIL",
                "DOMAIN",
                "ORGANIZATION",
                "WEBSITE",
                "REPOSITORY",
                "SOCIAL_ACCOUNT",
                "IP_ADDRESS",
                "CERTIFICATE",
                "DOCUMENT",
                name="entity_type",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=300), nullable=False),
        sa.Column("canonical_value", sa.String(length=1024), nullable=False),
        sa.Column(
            "aliases",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "confidence_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "type", "canonical_value", name="uq_entity_case_value"),
    )
    op.create_index(
        op.f("ix_entities_canonical_value"), "entities", ["canonical_value"], unique=False
    )
    op.create_index(op.f("ix_entities_case_id"), "entities", ["case_id"], unique=False)
    op.create_index("ix_entities_case_type", "entities", ["case_id", "type"], unique=False)
    op.create_index(op.f("ix_entities_confidence"), "entities", ["confidence"], unique=False)
    op.create_index(op.f("ix_entities_created_at"), "entities", ["created_at"], unique=False)
    op.create_index(op.f("ix_entities_type"), "entities", ["type"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("case_id", app.models.types.GUID(), nullable=False),
        sa.Column("celery_id", sa.String(length=64), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "COMPLETE",
                "FAILED",
                "CANCELLED",
                name="job_state",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_type", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "params",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_case_id"), "jobs", ["case_id"], unique=False)
    op.create_index("ix_jobs_case_state", "jobs", ["case_id", "state"], unique=False)
    op.create_index(op.f("ix_jobs_celery_id"), "jobs", ["celery_id"], unique=False)
    op.create_index(op.f("ix_jobs_created_at"), "jobs", ["created_at"], unique=False)
    op.create_index(op.f("ix_jobs_state"), "jobs", ["state"], unique=False)
    op.create_table(
        "targets",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("case_id", app.models.types.GUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "USERNAME",
                "DOMAIN",
                "EMAIL",
                "ORGANIZATION",
                "URL",
                "IP",
                "REPOSITORY",
                "SOCIAL_PROFILE",
                name="target_type",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("raw_input", sa.String(length=1024), nullable=False),
        sa.Column("normalized_value", sa.String(length=1024), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETE",
                "FAILED",
                "SKIPPED",
                name="target_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "type", "normalized_value", name="uq_target_case_value"),
    )
    op.create_index(op.f("ix_targets_case_id"), "targets", ["case_id"], unique=False)
    op.create_index("ix_targets_case_status", "targets", ["case_id", "status"], unique=False)
    op.create_index(op.f("ix_targets_created_at"), "targets", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_targets_normalized_value"), "targets", ["normalized_value"], unique=False
    )
    op.create_index(op.f("ix_targets_type"), "targets", ["type"], unique=False)
    op.create_table(
        "collector_runs",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("case_id", app.models.types.GUID(), nullable=False),
        sa.Column("target_id", app.models.types.GUID(), nullable=False),
        sa.Column("job_id", app.models.types.GUID(), nullable=True),
        sa.Column("collector", sa.String(length=64), nullable=False),
        sa.Column("collector_version", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCESS",
                "PARTIAL",
                "FAILED",
                "SKIPPED",
                "TIMEOUT",
                name="run_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("error_type", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "stats",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_collector_runs_case_id"), "collector_runs", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_collector_runs_collector"), "collector_runs", ["collector"], unique=False
    )
    op.create_index(
        op.f("ix_collector_runs_created_at"), "collector_runs", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_collector_runs_job_id"), "collector_runs", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_collector_runs_target_id"), "collector_runs", ["target_id"], unique=False
    )
    op.create_index(
        "ix_runs_case_collector", "collector_runs", ["case_id", "collector"], unique=False
    )
    op.create_index(
        "ix_runs_target_status", "collector_runs", ["target_id", "status"], unique=False
    )
    op.create_table(
        "relationships",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("case_id", app.models.types.GUID(), nullable=False),
        sa.Column("source_entity_id", app.models.types.GUID(), nullable=False),
        sa.Column("target_entity_id", app.models.types.GUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "USES_USERNAME",
                "OWNS_DOMAIN",
                "LINKS_TO",
                "MENTIONS",
                "MEMBER_OF",
                "CONTRIBUTED_TO",
                "HOSTED_ON",
                "RESOLVES_TO",
                "ISSUED_FOR",
                "REFERENCED_BY",
                "SAME_USERNAME",
                "POSSIBLY_SAME_ENTITY",
                "SUBDOMAIN_OF",
                "HAS_MX",
                "ARCHIVED_AS",
                name="relationship_type",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "confidence_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "strength",
            sa.Enum(
                "LIKELY_MATCH",
                "PROBABLE_MATCH",
                "POSSIBLE_MATCH",
                "WEAK_ASSOCIATION",
                name="match_strength",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("collector", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_entity_id", "target_entity_id", "type", name="uq_relationship_edge"
        ),
    )
    op.create_index(op.f("ix_relationships_case_id"), "relationships", ["case_id"], unique=False)
    op.create_index(
        "ix_relationships_case_type", "relationships", ["case_id", "type"], unique=False
    )
    op.create_index(
        "ix_relationships_confidence", "relationships", ["case_id", "confidence"], unique=False
    )
    op.create_index(
        op.f("ix_relationships_created_at"), "relationships", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_relationships_source_entity_id"),
        "relationships",
        ["source_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_relationships_target_entity_id"),
        "relationships",
        ["target_entity_id"],
        unique=False,
    )
    op.create_index(op.f("ix_relationships_type"), "relationships", ["type"], unique=False)
    op.create_table(
        "target_tags",
        sa.Column("target_id", app.models.types.GUID(), nullable=False),
        sa.Column("tag_id", app.models.types.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("target_id", "tag_id"),
    )
    op.create_table(
        "findings",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("case_id", app.models.types.GUID(), nullable=False),
        sa.Column("target_id", app.models.types.GUID(), nullable=True),
        sa.Column("run_id", app.models.types.GUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "DNS_RECORD",
                "DOMAIN_REGISTRATION",
                "HTTP_METADATA",
                "SECURITY_HEADER",
                "CERTIFICATE",
                "SUBDOMAIN",
                "ARCHIVE_SNAPSHOT",
                "REPOSITORY",
                "CODE_PROFILE",
                "COMMIT_ACTIVITY",
                "ORGANIZATION_MEMBERSHIP",
                "USERNAME_PRESENCE",
                "SEARCH_RESULT",
                "EMAIL_DOMAIN",
                "EXPOSURE_SUMMARY",
                "POTENTIAL_SECRET_EXPOSURE",
                "IP_REVERSE",
                "NOTE",
                name="finding_kind",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("collector", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "confidence_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "classification",
            sa.Enum(
                "PUBLIC",
                "PERSONAL",
                "SENSITIVE",
                "RESTRICTED",
                name="classification",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("redacted", sa.Boolean(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=128), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["collector_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_findings_case_classification", "findings", ["case_id", "classification"], unique=False
    )
    op.create_index(op.f("ix_findings_case_id"), "findings", ["case_id"], unique=False)
    op.create_index("ix_findings_case_kind", "findings", ["case_id", "kind"], unique=False)
    op.create_index(op.f("ix_findings_collector"), "findings", ["collector"], unique=False)
    op.create_index(op.f("ix_findings_confidence"), "findings", ["confidence"], unique=False)
    op.create_index(op.f("ix_findings_created_at"), "findings", ["created_at"], unique=False)
    op.create_index(
        "ix_findings_dedupe", "findings", ["case_id", "kind", "dedupe_key"], unique=False
    )
    op.create_index(op.f("ix_findings_dedupe_key"), "findings", ["dedupe_key"], unique=False)
    op.create_index(op.f("ix_findings_kind"), "findings", ["kind"], unique=False)
    op.create_index(op.f("ix_findings_run_id"), "findings", ["run_id"], unique=False)
    op.create_index(op.f("ix_findings_target_id"), "findings", ["target_id"], unique=False)
    op.create_table(
        "entity_sources",
        sa.Column("entity_id", app.models.types.GUID(), nullable=False),
        sa.Column("finding_id", app.models.types.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("entity_id", "finding_id"),
    )
    op.create_table(
        "evidence",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("case_id", app.models.types.GUID(), nullable=False),
        sa.Column("finding_id", app.models.types.GUID(), nullable=True),
        sa.Column("collector", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("raw_ref", sa.String(length=512), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("redacted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "sha256", name="uq_evidence_case_hash"),
    )
    op.create_index(
        "ix_evidence_case_collector", "evidence", ["case_id", "collector"], unique=False
    )
    op.create_index(op.f("ix_evidence_case_id"), "evidence", ["case_id"], unique=False)
    op.create_index(op.f("ix_evidence_created_at"), "evidence", ["created_at"], unique=False)
    op.create_index(op.f("ix_evidence_finding_id"), "evidence", ["finding_id"], unique=False)
    op.create_index(op.f("ix_evidence_sha256"), "evidence", ["sha256"], unique=False)
    op.create_table(
        "relationship_evidence",
        sa.Column("relationship_id", app.models.types.GUID(), nullable=False),
        sa.Column("finding_id", app.models.types.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["relationship_id"], ["relationships.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("relationship_id", "finding_id"),
    )
    op.create_table(
        "timeline_events",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("case_id", app.models.types.GUID(), nullable=False),
        sa.Column("finding_id", app.models.types.GUID(), nullable=True),
        sa.Column("entity_id", app.models.types.GUID(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("collector", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_timeline_case_kind", "timeline_events", ["case_id", "kind"], unique=False)
    op.create_index(
        "ix_timeline_case_occurred", "timeline_events", ["case_id", "occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_timeline_events_case_id"), "timeline_events", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_timeline_events_created_at"), "timeline_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_timeline_events_entity_id"), "timeline_events", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_timeline_events_finding_id"), "timeline_events", ["finding_id"], unique=False
    )
    op.create_index(op.f("ix_timeline_events_kind"), "timeline_events", ["kind"], unique=False)
    op.create_index(
        op.f("ix_timeline_events_occurred_at"), "timeline_events", ["occurred_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_timeline_events_occurred_at"), table_name="timeline_events")
    op.drop_index(op.f("ix_timeline_events_kind"), table_name="timeline_events")
    op.drop_index(op.f("ix_timeline_events_finding_id"), table_name="timeline_events")
    op.drop_index(op.f("ix_timeline_events_entity_id"), table_name="timeline_events")
    op.drop_index(op.f("ix_timeline_events_created_at"), table_name="timeline_events")
    op.drop_index(op.f("ix_timeline_events_case_id"), table_name="timeline_events")
    op.drop_index("ix_timeline_case_occurred", table_name="timeline_events")
    op.drop_index("ix_timeline_case_kind", table_name="timeline_events")
    op.drop_table("timeline_events")
    op.drop_table("relationship_evidence")
    op.drop_index(op.f("ix_evidence_sha256"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_finding_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_created_at"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_case_id"), table_name="evidence")
    op.drop_index("ix_evidence_case_collector", table_name="evidence")
    op.drop_table("evidence")
    op.drop_table("entity_sources")
    op.drop_index(op.f("ix_findings_target_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_run_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_kind"), table_name="findings")
    op.drop_index(op.f("ix_findings_dedupe_key"), table_name="findings")
    op.drop_index("ix_findings_dedupe", table_name="findings")
    op.drop_index(op.f("ix_findings_created_at"), table_name="findings")
    op.drop_index(op.f("ix_findings_confidence"), table_name="findings")
    op.drop_index(op.f("ix_findings_collector"), table_name="findings")
    op.drop_index("ix_findings_case_kind", table_name="findings")
    op.drop_index(op.f("ix_findings_case_id"), table_name="findings")
    op.drop_index("ix_findings_case_classification", table_name="findings")
    op.drop_table("findings")
    op.drop_table("target_tags")
    op.drop_index(op.f("ix_relationships_type"), table_name="relationships")
    op.drop_index(op.f("ix_relationships_target_entity_id"), table_name="relationships")
    op.drop_index(op.f("ix_relationships_source_entity_id"), table_name="relationships")
    op.drop_index(op.f("ix_relationships_created_at"), table_name="relationships")
    op.drop_index("ix_relationships_confidence", table_name="relationships")
    op.drop_index("ix_relationships_case_type", table_name="relationships")
    op.drop_index(op.f("ix_relationships_case_id"), table_name="relationships")
    op.drop_table("relationships")
    op.drop_index("ix_runs_target_status", table_name="collector_runs")
    op.drop_index("ix_runs_case_collector", table_name="collector_runs")
    op.drop_index(op.f("ix_collector_runs_target_id"), table_name="collector_runs")
    op.drop_index(op.f("ix_collector_runs_job_id"), table_name="collector_runs")
    op.drop_index(op.f("ix_collector_runs_created_at"), table_name="collector_runs")
    op.drop_index(op.f("ix_collector_runs_collector"), table_name="collector_runs")
    op.drop_index(op.f("ix_collector_runs_case_id"), table_name="collector_runs")
    op.drop_table("collector_runs")
    op.drop_index(op.f("ix_targets_type"), table_name="targets")
    op.drop_index(op.f("ix_targets_normalized_value"), table_name="targets")
    op.drop_index(op.f("ix_targets_created_at"), table_name="targets")
    op.drop_index("ix_targets_case_status", table_name="targets")
    op.drop_index(op.f("ix_targets_case_id"), table_name="targets")
    op.drop_table("targets")
    op.drop_index(op.f("ix_jobs_state"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_created_at"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_celery_id"), table_name="jobs")
    op.drop_index("ix_jobs_case_state", table_name="jobs")
    op.drop_index(op.f("ix_jobs_case_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_entities_type"), table_name="entities")
    op.drop_index(op.f("ix_entities_created_at"), table_name="entities")
    op.drop_index(op.f("ix_entities_confidence"), table_name="entities")
    op.drop_index("ix_entities_case_type", table_name="entities")
    op.drop_index(op.f("ix_entities_case_id"), table_name="entities")
    op.drop_index(op.f("ix_entities_canonical_value"), table_name="entities")
    op.drop_table("entities")
    op.drop_table("case_tags")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_index(op.f("ix_tags_created_at"), table_name="tags")
    op.drop_table("tags")
    op.drop_index("ix_cases_status_created", table_name="cases")
    op.drop_index(op.f("ix_cases_status"), table_name="cases")
    op.drop_index(op.f("ix_cases_name"), table_name="cases")
    op.drop_index(op.f("ix_cases_created_at"), table_name="cases")
    op.drop_table("cases")
    # ### end Alembic commands ###
