"""multi-factor authentication

Adds the second factor: one ``user_mfa`` row per account, a set of single-use
``mfa_recovery_codes``, and one column on ``user_sessions`` that decides whether
a session is actually authenticated.

**Existing accounts are unaffected.** No row is created for anybody, so every
account keeps signing in with a password alone until its owner enrols. There is
deliberately no backfill and no deployment-wide switch flipped here: turning MFA
on for a person who has not yet scanned a QR code would lock them out of their
own account.

**``user_sessions.mfa_satisfied_at`` is nullable and starts null**, including for
sessions that already exist when this runs. Those sessions belong to accounts
with no MFA enrolled, and :func:`app.services.accounts.session_requires_mfa`
reads the account's enrolment state, so a null on a non-enrolled account means
"nothing to satisfy" rather than "blocked". The column is only a gate for
accounts that have confirmed a factor.

**Downgrade destroys the second factor.** It drops both tables, so every enrolled
secret and every unused recovery code is gone and enrolled users fall back to a
password alone. That is recoverable — they can re-enrol. What is *not* recoverable
is downgrading further: ``dbeccf60fc7e`` drops users, workspaces, memberships,
sessions and the entire audit history. See docs/pilot-deployment.md.

Revision ID: 90102014feb7
Revises: dbeccf60fc7e
Create Date: 2026-09-18 12:42:21.787563
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql  # noqa: F401 - used by JSONB variants

import app.models.types
from alembic import op

revision: str = "90102014feb7"
down_revision: str | None = "dbeccf60fc7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mfa_recovery_codes",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("user_id", app.models.types.GUID(), nullable=False),
        sa.Column("code_hash", sa.String(length=512), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mfa_recovery_codes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mfa_recovery_codes_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_mfa_recovery_codes_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index("ix_recovery_user_used", ["user_id", "used_at"], unique=False)

    op.create_table(
        "user_mfa",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("user_id", app.models.types.GUID(), nullable=False),
        sa.Column("secret", sa.String(length=64), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_step", sa.Integer(), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_user_mfa_user"),
    )
    with op.batch_alter_table("user_mfa", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_mfa_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_mfa_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("mfa_satisfied_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_column("mfa_satisfied_at")

    with op.batch_alter_table("user_mfa", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_mfa_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_mfa_created_at"))

    op.drop_table("user_mfa")
    with op.batch_alter_table("mfa_recovery_codes", schema=None) as batch_op:
        batch_op.drop_index("ix_recovery_user_used")
        batch_op.drop_index(batch_op.f("ix_mfa_recovery_codes_user_id"))
        batch_op.drop_index(batch_op.f("ix_mfa_recovery_codes_created_at"))

    op.drop_table("mfa_recovery_codes")
    # ### end Alembic commands ###
