"""record collector source attribution on runs

Revision ID: a12e580fbbc3
Revises: d625ca41c9fd
Create Date: 2026-09-03 22:11:55.853509
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql  # noqa: F401 - used by JSONB variants

import app.models.types  # noqa: F401 - used by GUID columns
from alembic import op

revision: str = "a12e580fbbc3"
down_revision: str | None = "d625ca41c9fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collector_runs", sa.Column("source_attribution", sa.String(length=200), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collector_runs", "source_attribution")
    # ### end Alembic commands ###
