"""accounts, workspaces, sessions and the audit ledger

Five new tables and one new column, turning "anybody who knows a UUID" into
"a member of the workspace that owns it".

    users                   one person who can sign in
    workspaces              a tenant
    workspace_memberships   what one user may do in one workspace
    user_sessions           one signed-in browser
    audit_events            append-only security record
    cases.workspace_id      the containment boundary

**No investigation data is touched.** Not one row of cases, targets, findings,
evidence, entities, relationships, timeline events, collector runs, jobs,
observations, social profiles, images, public contacts or analyst decisions is
read, rewritten or deleted here. The only change to an existing table is a new
nullable column on ``cases``.

**Existing cases are left unclaimed, on purpose.** ``cases.workspace_id`` is
nullable and is *not* backfilled. There is no workspace to backfill it to at
migration time, and inventing one — or attaching every historical case to
whoever happens to run ``create-admin`` first — would hand one operator a
customer's back catalogue on the strength of being early. So an upgraded
installation starts with its cases present in the database and invisible to the
API, and an operator adopts them deliberately:

    python -m app.cli create-admin          # first user, first workspace
    python -m app.cli claim-cases --workspace <slug>   # explicit, reversible

``claim-cases`` prints what it is about to do and requires confirmation. See
``docs/pilot-deployment.md`` -> *Upgrading an existing installation*.

The nullable column is also what makes the downgrade safe: dropping it returns
the database to exactly the pre-workspace schema, and every case is reachable
again by the pre-upgrade code. The foreign key is ``RESTRICT`` rather than
``CASCADE`` so that deleting a workspace can never silently delete a customer's
investigations; the API refuses to delete a workspace that still owns cases.

Revision ID: dbeccf60fc7e
Revises: 583ddee18357
Create Date: 2026-09-13 12:26:47.716867
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.models.types
from alembic import op

revision: str = "dbeccf60fc7e"
down_revision: str | None = "583ddee18357"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "workspaces",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workspaces", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workspaces_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_workspaces_slug"), ["slug"], unique=True)

    op.create_table(
        "audit_events",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_user_id", app.models.types.GUID(), nullable=True),
        sa.Column("workspace_id", app.models.types.GUID(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "USER_LOGIN_SUCCESS",
                "USER_LOGIN_FAILURE",
                "USER_LOGOUT",
                "USER_CREATED",
                "MEMBERSHIP_ADDED",
                "MEMBERSHIP_REMOVED",
                "ROLE_CHANGED",
                "OWNERSHIP_TRANSFERRED",
                "CASE_CREATED",
                "CASE_DELETED",
                "INVESTIGATION_STARTED",
                "INVESTIGATION_CANCELLED",
                "REPORT_GENERATED",
                "REPORT_DOWNLOADED",
                "ANALYST_DECISION_CREATED",
                "MANUAL_RESULT_IMPORTED",
                "RATE_LIMIT_TRIGGERED",
                name="audit_event",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("object_type", sa.String(length=40), nullable=False),
        sa.Column("object_id", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index("ix_audit_actor_time", ["actor_user_id", "occurred_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_actor_user_id"), ["actor_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_workspace_id"), ["workspace_id"], unique=False
        )
        batch_op.create_index("ix_audit_type_time", ["event_type", "occurred_at"], unique=False)
        batch_op.create_index(
            "ix_audit_workspace_time", ["workspace_id", "occurred_at"], unique=False
        )

    op.create_table(
        "user_sessions",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("user_id", app.models.types.GUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.create_index("ix_sessions_user_expires", ["user_id", "expires_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_user_sessions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_sessions_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_user_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "workspace_memberships",
        sa.Column("id", app.models.types.GUID(), nullable=False),
        sa.Column("user_id", app.models.types.GUID(), nullable=False),
        sa.Column("workspace_id", app.models.types.GUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "ADMIN",
                "ANALYST",
                "VIEWER",
                name="workspace_role",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "workspace_id", name="uq_membership_user_workspace"),
    )
    with op.batch_alter_table("workspace_memberships", schema=None) as batch_op:
        batch_op.create_index(
            "ix_membership_workspace_role", ["workspace_id", "role"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workspace_memberships_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workspace_memberships_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workspace_memberships_workspace_id"), ["workspace_id"], unique=False
        )

    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("workspace_id", app.models.types.GUID(), nullable=True))
        batch_op.create_index(
            "ix_cases_workspace_created", ["workspace_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_cases_workspace_id"), ["workspace_id"], unique=False)
        # Named, because an unnamed constraint cannot be dropped again on
        # PostgreSQL — the downgrade would fail with "constraint None".
        batch_op.create_foreign_key(
            "fk_cases_workspace_id", "workspaces", ["workspace_id"], ["id"], ondelete="RESTRICT"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_constraint("fk_cases_workspace_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_cases_workspace_id"))
        batch_op.drop_index("ix_cases_workspace_created")
        batch_op.drop_column("workspace_id")

    with op.batch_alter_table("workspace_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workspace_memberships_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_workspace_memberships_user_id"))
        batch_op.drop_index(batch_op.f("ix_workspace_memberships_created_at"))
        batch_op.drop_index("ix_membership_workspace_role")

    op.drop_table("workspace_memberships")
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_sessions_token_hash"))
        batch_op.drop_index(batch_op.f("ix_user_sessions_created_at"))
        batch_op.drop_index("ix_sessions_user_expires")

    op.drop_table("user_sessions")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_workspace_time")
        batch_op.drop_index("ix_audit_type_time")
        batch_op.drop_index(batch_op.f("ix_audit_events_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_audit_events_actor_user_id"))
        batch_op.drop_index("ix_audit_actor_time")

    op.drop_table("audit_events")
    with op.batch_alter_table("workspaces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workspaces_slug"))
        batch_op.drop_index(batch_op.f("ix_workspaces_created_at"))

    op.drop_table("workspaces")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_index(batch_op.f("ix_users_created_at"))

    op.drop_table("users")
    # ### end Alembic commands ###
