"""Bounded, deterministic name variants — and what a variant is worth.

An investigation for "Tabitha Afzal Imdad" found nothing, because public sources
write the same person as "Tabitha Afzal". Searching only the canonical spelling
is too literal to be useful.

Two ideas keep that from becoming a licence to guess.

**Variants are generated by rule, never by permutation.** Every variant comes
from one of four named transformations, each of which a person could plausibly
have used about themselves, and each carries the rule that produced it. A
four-part name does not become twenty-four searches: the rules are bounded by
construction and capped besides.

**A variant is a discovery signal, not an identity claim.** Finding "Tabitha
Afzal" while investigating "Tabitha Afzal Imdad" is a reason to *look*, never a
reason to believe. A reduced name matches more strangers than the full one, so
its relationship is recorded explicitly and it scores *below* an exact match —
and nothing in this module touches the target, which keeps the canonical name
the investigator typed.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass
from typing import Any

#: Variant kinds, ordered strongest first. The order is the confidence order:
#: an exact spelling is worth more than a dropped name part, and every consumer
#: reads that from here rather than deciding for itself.
EXACT = "EXACT_NAME"
#: The source publishes a *fuller* name that contains every searched part —
#: "Tabitha Afzal Imdad" for a search of "Tabitha Afzal". Not a variant we
#: generate (we cannot invent a name part nobody gave us), but one a source may
#: use, and it is not weaker than the exact spelling: nothing searched for is
#: missing, so it fires the same rule.
EXTENDED = "EXTENDED_NAME_MATCH"
HYPHENATION = "HYPHENATION_VARIANT"
INITIAL = "INITIAL_VARIANT"
REDUCED = "REDUCED_NAME_VARIANT"
PARTIAL = "PARTIAL_NAME_MATCH"

VARIANT_ORDER: tuple[str, ...] = (EXACT, EXTENDED, HYPHENATION, INITIAL, REDUCED, PARTIAL)

#: What each kind means, for a report and for the investigator reading it.
VARIANT_LABELS: dict[str, str] = {
    EXACT: "Exact name as supplied",
    EXTENDED: "A fuller name containing every part supplied",
    HYPHENATION: "Same parts, joined with a hyphen",
    INITIAL: "A middle name shortened to its initial",
    REDUCED: "One name part dropped — a shorter form in public use",
    PARTIAL: "Shares some name parts with the subject",
}

#: How much each kind may contribute *as a name match*. These are ceilings on
#: the name signal alone, not scores: a reduced name can never be stronger
#: evidence than the full spelling, and none of them identifies anybody.
VARIANT_NAME_WEIGHT: dict[str, float] = {
    EXACT: 1.0,
    EXTENDED: 1.0,
    HYPHENATION: 0.9,
    INITIAL: 0.8,
    REDUCED: 0.5,
    PARTIAL: 0.3,
}

#: The named confidence rule each variant kind fires as its *name* signal.
#: A variant kind with no rule here cannot influence a score at all, which keeps
#: the scoring surface closed and reviewable.
VARIANT_CONFIDENCE_RULES: dict[str, str] = {
    EXACT: "same_person_name",
    # Every searched part is present, so the same rule as an exact spelling.
    EXTENDED: "same_person_name",
    HYPHENATION: "name_variant_hyphenation",
    INITIAL: "name_variant_initial",
    REDUCED: "name_variant_reduced",
    PARTIAL: "name_variant_partial",
}


def confidence_rule_for(variant_type: str) -> str:
    """The name rule a variant kind fires. Unknown kinds get the weakest."""
    return VARIANT_CONFIDENCE_RULES.get(variant_type, VARIANT_CONFIDENCE_RULES[PARTIAL])


#: Variants generated per name. A worklist, not a permutation space.
MAX_VARIANTS = 8
#: Name parts beyond this and only the exact spelling is searched. A long name
#: is usually a transliteration or a compound, and dropping parts from one
#: invents people rather than finding one.
MAX_PARTS_FOR_VARIANTS = 4
#: Particles that belong to the name part after them rather than standing alone.
PARTICLES = frozenset(
    {
        "al",
        "bin",
        "bint",
        "da",
        "de",
        "del",
        "della",
        "der",
        "di",
        "dos",
        "du",
        "el",
        "ibn",
        "la",
        "le",
        "mac",
        "mc",
        "san",
        "santa",
        "st",
        "ter",
        "van",
        "von",
        "zu",
    }
)

_WHITESPACE_RE = re.compile(r"\s+")


@dataclass(frozen=True, slots=True)
class NameVariant:
    """One spelling to search for, and why it exists."""

    #: The spelling itself, ready to quote into a query.
    value: str
    #: One of the module constants above.
    variant_type: str
    #: The canonical name the investigator supplied. Never rewritten.
    canonical: str
    #: Why this spelling was generated, in a sentence an investigator reads.
    reason: str

    @property
    def is_exact(self) -> bool:
        return self.variant_type == EXACT

    @property
    def name_weight(self) -> float:
        return VARIANT_NAME_WEIGHT.get(self.variant_type, VARIANT_NAME_WEIGHT[PARTIAL])

    @property
    def key(self) -> str:
        """Identity for *comparison*: the folded spelling.

        Punctuation-insensitive, because "Tabitha A. Imdad" and "Tabitha A
        Imdad" name the same person.
        """
        return fold_name(self.value)

    @property
    def search_key(self) -> str:
        """Identity for *generation*: the literal spelling, case-folded.

        Deliberately not :attr:`key`. A search engine treats "Tabitha A. Imdad"
        and "Tabitha A Imdad" as different queries, so both are worth running —
        deduplicating them on the folded form silently dropped the variants this
        module exists to produce.
        """
        return _WHITESPACE_RE.sub(" ", self.value.strip()).lower()

    def to_dict(self) -> dict[str, Any]:
        return {
            "search_variant": self.value,
            "variant_type": self.variant_type,
            "variant_label": VARIANT_LABELS.get(self.variant_type, self.variant_type),
            "canonical_target": self.canonical,
            "variant_generation_reason": self.reason,
            "name_weight": self.name_weight,
        }


def fold_name(text: str) -> str:
    """Lower-case, strip accents and punctuation, collapse whitespace.

    For comparison only. The displayed spelling is always what the source or the
    investigator wrote — folding is how two spellings are *compared*, never how
    either is stored.
    """
    decomposed = unicodedata.normalize("NFKD", text or "")
    stripped = "".join(char for char in decomposed if not unicodedata.combining(char))
    cleaned = re.sub(r"[^\w\s]+", " ", stripped, flags=re.UNICODE)
    return _WHITESPACE_RE.sub(" ", cleaned).strip().lower()


def name_parts(text: str) -> list[str]:
    """The name's parts, with particles attached to the part they qualify.

    "van der Berg" is three tokens and one surname. Treating the particles as
    droppable parts would produce "Anna van" and "Anna der", which are not
    names anybody uses.
    """
    tokens = [token for token in _WHITESPACE_RE.split((text or "").strip()) if token]
    parts: list[str] = []
    pending: list[str] = []
    for token in tokens:
        if fold_name(token) in PARTICLES:
            pending.append(token)
            continue
        parts.append(" ".join([*pending, token]) if pending else token)
        pending = []
    if pending:
        # Trailing particles are not a name part of their own; keep them on the
        # last real part rather than dropping what the investigator typed.
        if parts:
            parts[-1] = f"{parts[-1]} {' '.join(pending)}"
        else:
            parts = [" ".join(pending)]
    return parts


def generate_variants(name: str) -> list[NameVariant]:
    """Every spelling worth searching for ``name``, strongest first.

    Deterministic: the same input always produces the same list in the same
    order, so a case re-opened a week later shows the investigator what they saw
    before.
    """
    canonical = _WHITESPACE_RE.sub(" ", (name or "").strip())
    if not canonical:
        return []

    variants: list[NameVariant] = [
        NameVariant(
            value=canonical,
            variant_type=EXACT,
            canonical=canonical,
            reason="The name exactly as you supplied it.",
        )
    ]
    parts = name_parts(canonical)

    if len(parts) < 2:
        # A single token is a handle, a mononym or a fragment. There is nothing
        # to reduce, and inventing a second part would invent a person.
        return variants
    if len(parts) > MAX_PARTS_FOR_VARIANTS:
        return variants

    seen = {variants[0].search_key}

    def add(value: str, variant_type: str, reason: str) -> None:
        candidate = NameVariant(
            value=_WHITESPACE_RE.sub(" ", value.strip()),
            variant_type=variant_type,
            canonical=canonical,
            reason=reason,
        )
        if candidate.search_key in seen or not candidate.value or len(variants) >= MAX_VARIANTS:
            return
        seen.add(candidate.search_key)
        variants.append(candidate)

    first, last = parts[0], parts[-1]
    middles = parts[1:-1]

    # --- INITIAL: a middle name shortened, the commonest published form.
    for index, middle in enumerate(middles):
        letter = _initial(middle)
        if not letter:
            continue
        shortened = [*parts]
        shortened[index + 1] = letter
        add(
            " ".join(shortened),
            INITIAL,
            f"{middle!r} shortened to its initial — how a middle name is usually published.",
        )
        shortened[index + 1] = f"{letter}."
        add(
            " ".join(shortened),
            INITIAL,
            f"{middle!r} shortened to {letter}., the same form with a full stop.",
        )

    # --- REDUCED: one part dropped. First and last are kept in every variant,
    #     because a name without either is not a shorter form of this name.
    for index, middle in enumerate(middles):
        kept = [part for position, part in enumerate(parts[1:-1]) if position != index]
        add(
            " ".join([first, *kept, last]),
            REDUCED,
            f"{middle!r} dropped — public sources often omit a middle name. A shorter "
            f"form is shared by more people, so a hit is a lead until something "
            f"independent corroborates it.",
        )
    # Dropping the *last* part is only offered for a three-part name, where it
    # leaves two parts and is a form people genuinely publish ("Tabitha Afzal").
    # On a longer name the same rule would drop two parts at once, which is less
    # a shorter form than a different name.
    if len(parts) == 3:
        add(
            f"{first} {middles[0]}",
            REDUCED,
            f"{last!r} dropped, leaving {first} {middles[0]} — a form in common public "
            f"use. A shorter form is shared by more people, so a hit is a lead until "
            f"something independent corroborates it.",
        )

    # --- HYPHENATION: the last two parts joined, and an existing hyphen opened.
    if len(parts) >= 3:
        add(
            f"{' '.join(parts[:-2])} {parts[-2]}-{last}".strip(),
            HYPHENATION,
            f"{parts[-2]} and {last} joined with a hyphen, as a double-barrelled surname.",
        )
    if "-" in canonical:
        add(
            canonical.replace("-", " "),
            HYPHENATION,
            "An existing hyphen opened out into a space.",
        )

    # Strongest kind first, then alphabetically, so the list is stable and the
    # order an investigator reads matches the order of evidential weight.
    return sorted(
        variants,
        key=lambda item: (VARIANT_ORDER.index(item.variant_type), item.value.lower()),
    )


def _initial(part: str) -> str:
    """The first letter of a name part, upper-cased, or empty if it has none."""
    for char in part:
        if char.isalpha():
            return char.upper()
    return ""


def classify_observed_name(observed: str, canonical: str) -> tuple[str, str]:
    """How a name a source published relates to the canonical one.

    Returns ``(variant_type, explanation)``. This is the read-side counterpart
    of :func:`generate_variants`: a source did not have to use one of our
    spellings, and what it did use still has to be described honestly.
    """
    observed_clean = _WHITESPACE_RE.sub(" ", (observed or "").strip())
    if not observed_clean:
        return PARTIAL, "The source publishes no name to compare."
    if fold_name(observed_clean) == fold_name(canonical):
        if observed_clean.lower() == canonical.lower():
            return EXACT, f"The source spells the name exactly as supplied ({observed_clean!r})."
        # Same parts, different punctuation — a hyphenated surname, usually.
        return HYPHENATION, (
            f"The source writes {observed_clean!r}: the same name parts as {canonical!r}, "
            f"punctuated differently."
        )

    for variant in generate_variants(canonical):
        if variant.key == fold_name(observed_clean):
            return variant.variant_type, variant.reason

    observed_parts = {fold_name(part) for part in name_parts(observed_clean)}
    canonical_parts = {fold_name(part) for part in name_parts(canonical)}
    shared = observed_parts & canonical_parts
    if canonical_parts and canonical_parts < observed_parts:
        extra = sorted(observed_parts - canonical_parts)
        return EXTENDED, (
            f"The source publishes {observed_clean!r}, which carries every part of "
            f"{canonical!r} plus {', '.join(extra)!r}. Nothing searched for is missing."
        )
    if observed_parts and observed_parts < canonical_parts:
        return REDUCED, (
            f"The source publishes {observed_clean!r}, a shorter form of {canonical!r}. "
            f"Shorter forms match more people, so this is a lead rather than a match."
        )
    if shared:
        return PARTIAL, (
            f"The source publishes {observed_clean!r}, which shares "
            f"{', '.join(sorted(shared))!r} with {canonical!r} and differs elsewhere."
        )
    return PARTIAL, (
        f"The source publishes {observed_clean!r}, which shares no name part with {canonical!r}."
    )


def variant_for(value: str, variants: list[NameVariant]) -> NameVariant | None:
    """The variant whose spelling is ``value``, if one of ours produced it."""
    folded = fold_name(value)
    return next((variant for variant in variants if variant.key == folded), None)
